### PR TITLE
Delete 'vue/cli' dependency and updated dependecies:

### LINKED ISSUE #43: Dependecies are out of date
Dependecies are out of date:
Electron: 22.0.2 => 23.0.0
Vite: 4.0.4 => 4.1.1
Vue: 3.2.40 => 3.2.47

`@vue/cli` is a tool based on `webpack`, in this case, it is not needed by this template. If there is any other concerns, this dependency should be kept.
:smil:

### PR DESCRIPTION
**Pull request by onequid**
Vue: 3.2.47
Vite: 4.1.1
Electron: 23.0.0
Closed #43

### CODE REVIEW

**Comment by Deluze** [comment]
Hi. Thanks for opening this PR. Electron 23 just came out and I'm willing to merge this PR to keep that version up-to-date 👍The Vue CLI was indeed an unused dev dependency, so removing it makes sense.

Locally I'm running against some issues when upgrading to Electron ^23.0, as Electron outputs the following error:

```shell
[electron] Hello from App.vue!
[electron] [55344:0213/224634.753:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate
```

I don't have this issue on Electron < 23.0. I'm curious what's going on; I haven't found any related Electron issues yet on their GH. So I want to do a little bit more digging on what's causing this before merging 😄

**Comment by onequid** [comment]
Hi Dueluze, thanks for your comment. Your views make perfect sense! Cheers! 💯 
And it seems a certificate issue as the message shows. I haven't got this notification yet, so sorry for no clues. 
Will clean the node_modules make any progress as it comes first to my thought?

**Comment by Deluze** [comment]
I believe the error is coming from trying to load the Vue logo. Loading in other external assets seem to work just fine. I'll update this template to match the project generated by running `npm create vite@latest --template vue`

**Comment by Deluze** [comment]
@onequid Could you run the `npm update` command on the Vue/Vite/Electron dependencies so the lock file reflects these new versions? The error has nothing to do with your changes, so we can merge the PR after the lock file is updated 👍

**Comment by onequid** [comment]
Copy that,  Captain. 
Glad to make one tiny coneibution for this repo 😄  
 I will do that ASAP when I get back to my workstation on Monday.  Hope that'd be OK.

**Comment by onequid** [comment]
Hopefully I did it correctly 😄

**Comment by Deluze** [comment]
Looks good! Thanks for keeping the dependencies up-to-date :)

**Pull request merged**
