### PR TITLE
copy static files of main in building process

### PR DESCRIPTION
**Pull request by zhanglongqi**

### CODE REVIEW

**Comment by Deluze** [comment]
Why is this change needed? 

The static files actually don't have to be copied over to the build dir. Electron Builder actually pulls the static files from the src directory when the app gets compiled.

**Comment by zhanglongqi** [comment]
we need it when `npm run dev`

**Comment by zhanglongqi** [comment]
sorry, the modification should be in `dev-server.js` 
I add this because I need to access the image file in the main process.

**Comment by Deluze** [comment]
I just noticed. You're correct, this broke after we migrated to TS.

I don't think there's a way to avoid this right? I'm thinking about the devs that have larger files in their static directory, it would need to get copied on every start up.

Maybe to make the process go faster, we can use `Promise.allSettled` so we can copy the files, and let the dev server start up at the same time asynchronously.

I'll test your change and if everything works perfectly I'll merge it 👍

**Comment by Deluze** [comment]
I just noticed. You're correct, this broke after we migrated to TS.

I don't think there's a way to avoid this right? I'm thinking about the devs that have larger files in their static directory, it would need to get copied on every start up.

Maybe to make the process go faster, we can use `Promise.allSettled` so we can copy the files, and let the dev server start up at the same time asynchronously.

I'll test your change and if everything works perfectly I'll merge it 👍

**Review by Deluze — APPROVED** [review]

**Comment by Deluze** [comment]
Looks good, one thing I noticed is that the `cpSync` method got introduced in 16.x, so the minimum version of node this template with is 16.x now.

Not a problem for me 😄 seems that node LTS is currently on 16.x. Nice!

Thank you for contributing. It means a lot.

**Pull request merged**
